services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    volumes:
      - ./redis:/var/lib/redis
      - ./redis/config:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
    networks:
      - nextcloud-net

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
    networks:
      - nextcloud-net

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_DOMAIN}
      OVERWRITEHOST: ${NEXTCLOUD_DOMAIN}
      OVERWRITEPROTOCOL: ${NEXTCLOUD_PROTOCOL}
      TRUSTED_PROXIES: ${NEXTCLOUD_TRUSTED_PROXY}
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/themes:/var/www/html/themes
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - nextcloud-net

  cron:
    container_name: cron
    image: nextcloud:latest
    restart: always
    entrypoint: /cron.sh
    volumes:
      - ./nextcloud/html:/var/www/html
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
