services:
  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    volumes:
      - ./redis:/var/lib/redis
      - ./redis/config:/usr/local/etc/redis/redis.conf
    networks:
      - nextcloud-net

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed --innodb-buffer-pool-size=2G --innodb-log-file-size=128M --innodb-log-buffer-size=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nextcloud-net

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
    volumes:
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
